title: Positional Embeddings
slug: positional-embeddings
difficulty: intermediate
prerequisites: [attention]
tags: [position, embeddings, rope, sinusoidal]
estimated_time_minutes: 90
last_updated: 2025-08-11
